INSERT INTO BANCA VALUES (1, 'Banca BT', 'Loc1', 3);
INSERT INTO BANCA VALUES (2, 'Banca BRD', 'Loc2', 2);
INSERT INTO BANCA VALUES (3, 'Banca BCR', 'Loc3', 5);
INSERT INTO BANCA VALUES (4, 'Banca ING', 'Loc4', 3);
INSERT INTO BANCA VALUES (5, 'Banca TBIBANK', 'Loc5', 2);