  CREATE TABLE "BANCA" 
   (	"BANCA_ID" NUMBER, 
	"NUME_BANCA" VARCHAR2(255) NOT NULL ENABLE, 
	"LOCATIE" VARCHAR2(255), 
	"NR_SUCURSALE" NUMBER, 
	 PRIMARY KEY ("BANCA_ID")
  USING INDEX  ENABLE
   ) ;

   COMMENT ON COLUMN "BANCA"."NUME_BANCA" IS 'Numele băncii';
   COMMENT ON COLUMN "BANCA"."LOCATIE" IS 'Locația băncii';
   COMMENT ON COLUMN "BANCA"."NR_SUCURSALE" IS 'Numărul de sucursale al băncii';