  CREATE TABLE "CLIENT" 
   (	"CLIENT_ID" NUMBER, 
	"BANCA_ID" NUMBER, 
	"NUME" VARCHAR2(255) NOT NULL ENABLE, 
	"PRENUME" VARCHAR2(255) NOT NULL ENABLE, 
	"DATA_NASTERII" DATE, 
	"ADRESE" VARCHAR2(255), 
	"NR_TELEFON" VARCHAR2(20), 
	 PRIMARY KEY ("CLIENT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CLIENT" ADD FOREIGN KEY ("BANCA_ID")
	  REFERENCES "BANCA" ("BANCA_ID") ENABLE;

   COMMENT ON COLUMN "CLIENT"."NUME" IS 'Numele clientului';
   COMMENT ON COLUMN "CLIENT"."PRENUME" IS 'Prenumele clientului';
   COMMENT ON COLUMN "CLIENT"."DATA_NASTERII" IS 'Data nașterii a clientului';
   COMMENT ON COLUMN "CLIENT"."ADRESE" IS 'Adresa clientului';
   COMMENT ON COLUMN "CLIENT"."NR_TELEFON" IS 'Numărul de telefon al clientului';