  CREATE TABLE "CONT_BANCAR" 
   (	"CONT_ID" NUMBER, 
	"BANCA_ID" NUMBER, 
	"CLIENT_ID" NUMBER, 
	"TIP_CONT" VARCHAR2(50) NOT NULL ENABLE, 
	"SOLD" NUMBER, 
	"DATA_DESCHIDERII" DATE, 
	"STATUS" VARCHAR2(50), 
	 PRIMARY KEY ("CONT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CONT_BANCAR" ADD FOREIGN KEY ("BANCA_ID")
	  REFERENCES "BANCA" ("BANCA_ID") ENABLE;
  ALTER TABLE "CONT_BANCAR" ADD FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "CLIENT" ("CLIENT_ID") ENABLE;

   COMMENT ON COLUMN "CONT_BANCAR"."TIP_CONT" IS 'Tipul contului bancar';
   COMMENT ON COLUMN "CONT_BANCAR"."SOLD" IS 'Soldul contului bancar';
   COMMENT ON COLUMN "CONT_BANCAR"."DATA_DESCHIDERII" IS 'Data deschiderii contului bancar';
   COMMENT ON COLUMN "CONT_BANCAR"."STATUS" IS 'Starea contului bancar';