  CREATE TABLE "DETALIU_TRANZACTII" 
   (	"DETALIU_ID" NUMBER, 
	"CONT_ID" NUMBER, 
	"TRANZACTIE_ID" NUMBER, 
	"SUMA_TRANZACTIONALA" NUMBER, 
	 PRIMARY KEY ("DETALIU_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DETALIU_TRANZACTII" ADD FOREIGN KEY ("CONT_ID")
	  REFERENCES "CONT_BANCAR" ("CONT_ID") ENABLE;
  ALTER TABLE "DETALIU_TRANZACTII" ADD FOREIGN KEY ("TRANZACTIE_ID")
	  REFERENCES "TRANZACTIE" ("TRANZACTIE_ID") ENABLE;

   COMMENT ON COLUMN "DETALIU_TRANZACTII"."SUMA_TRANZACTIONALA" IS 'Suma tranzacționată';