  CREATE TABLE "TRANZACTIE" 
   (	"TRANZACTIE_ID" NUMBER, 
	"DATA_TRANZACTIEI" DATE, 
	"SUMA" NUMBER, 
	"TIP_TRANZACTIE" VARCHAR2(50), 
	"CLIENT_ID" NUMBER, 
	 PRIMARY KEY ("TRANZACTIE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "TRANZACTIE" ADD FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "CLIENT" ("CLIENT_ID") ENABLE;

   COMMENT ON COLUMN "TRANZACTIE"."DATA_TRANZACTIEI" IS 'Data tranzacției';
   COMMENT ON COLUMN "TRANZACTIE"."SUMA" IS 'Suma tranzacției';
   COMMENT ON COLUMN "TRANZACTIE"."TIP_TRANZACTIE" IS 'Tipul tranzacției';